### ISSUE TITLE
provide correct filename for store/save dialogs

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/WebACS#16]
if a model is downloaded from the ARE (in order to make changes using the webACS) 
it should be possible to store the changes to the same model file on the ARE. 
When "Store Model on ARE" is clicked, a default model filename is suggested "e.g. newFile.acs" - the user has no option to overwrite/update the original file.

It would be good to provide the original path/filename of the downloaded model in order to allow updates of this model via the "store model on ARE"  dialog or use the original model name for the "save model" dialog.

**Comment by kingcole** [comment]
hm...I cannot reconstruct the problem. when I download a model from ARE storage, it is given the filename under which it is stored - when I then try to store it on the ARE again, it is exactly that filename that is suggested. when I then click "store", I am asked if I want to overwrite the file and when I click "yes" it is overwritten. I guess this is the behaviour you are asking for, isn't it? works for me...
could it be that you are mixing up "Download Model" and "Load model from storage"? if you use "download model" you download the currently active model from the ARE - in this case you get a default filename, because I have no way of knowing if this model is already in ARE storage or not. however, if you use "Load model from storage", I know a filename and it is used.

**Comment by deinhofer** [comment]
> hm...I cannot reconstruct the problem. when I download a model from ARE storage, it is given the filename under which it is stored - when I then try to store it on the ARE again, it is exactly that filename that is suggested. when I then click "store", I am asked if I want to overwrite the file and when I click "yes" it is overwritten. I guess this is the behaviour you are asking for, isn't it? works for me...
> could it be that you are mixing up "Download Model" and "Load model from storage"? if you use "download model" you download the currently active model from the ARE - in this case you get a default filename, because I have no way of knowing if this model is already in ARE storage or not. however, if you use "Load model from storage", I know a filename and it is used.

I think kingcole is right, if you click 'Download Model' the filename is not known, as it is just a model object in the ARE memory.
--> will close the issue.
