### ISSUE TITLE
GUI designer does not sanitize plugin GUI coordinates if the are outside of visible area

### ISSUE THREAD

**Issue by deinhofer** [asterics/WebACS#42]
If you open a model containing ARE-GUI widgets with coordiniates in a non-visible area the GUI-designer does not sanitize the coordinates. This way it can happen, that the widget is not visible in the ARE GUI windows.

![image](https://user-images.githubusercontent.com/4621810/60187927-c145b780-982e-11e9-9d81-a9f4f7aeb564.png)
  
## Solution

* Do sanity check, if the coordinates are within the GUI boundaries.
* Additionally the ARE should also check if the widgets are within the screen dimensions.

**Comment by ChrisVeigl** [comment]
it's not a bug - it's a feature !  ;-)
actually we decided to implement it that way because there are (have been) cases where it made sense to place the gui of a plugin outside the visible area - or place it in a way that it is only partly visible.
as long as this does not impose a problem i'd suggest to keep it that way ...

**Comment by kingcole** [comment]
hm...you might have decided that for the old ACS - but when implementing the WebACS I did not know of that decision and actually implemented it otherwise, which used to work. I have a 3-month-old version of the WebACS here, where the plugin stays inside the boundaries, i.e. I cannot do what Martin did in his screenshot. I'd assume that some newer changes broke something here...

**Comment by sabicalija** [comment]
I would be surprised if any of the newer changes have broken something wrt. the GUI designer. Since there are no updates on that part - AFAIK. That `3-month-old` version you're referring to: can you give us a commit ID or something similar so that we can test the difference? Thanks! :bowtie:

**Comment by kingcole** [comment]
ok, after taking a closer look, I have to apologize twice - once for saying 3-month, although it is a commit from last year (https://github.com/asterics/WebACS/commit/e61e1948bdb5016278daacb5329d21e91ab0a69e) and once for note reading properly - you said "open" a model, not "create". Ok, so yes, opening a model that has coordinates out of vision will leave them there - that is indeed a case I did not think of - mainly because I wouldn't know where such a model could come from (assuming that people do not manually edit a model-XML). Now knowing that the old ACS allows to move things out of view, things are of course different.
Btw. the WebACS does correct the coordinates as soon as anything is moved in the GUI editor.

**Comment by deinhofer** [comment]
actually I think the title of the issue is not good. It's just about the case that if a model file contains coordinates outside of the screen area they are not sanitized.
@ChrisVeigl said that he needs this ```feature``` for being able to make GUI components of a plugin invisible. 
I think that it's a dirty solution for making GUI components invisible but nevertheless it's a good workaround until plugin properties allow to do that generically.

--> I will rename the issue and close it.
